-- ============================================================
-- 08_COST_GOVERNANCE.sql
-- Resource monitors for cost control
-- ============================================================

-- Warehouse-level monitor (COMPUTE_WH)
CREATE OR REPLACE RESOURCE MONITOR EV_PIPELINE_MONITOR
  WITH CREDIT_QUOTA = 20
  FREQUENCY = MONTHLY
  START_TIMESTAMP = IMMEDIATELY
  TRIGGERS
    ON 75 PERCENT DO NOTIFY
    ON 95 PERCENT DO SUSPEND
    ON 100 PERCENT DO SUSPEND_IMMEDIATE;

ALTER WAREHOUSE COMPUTE_WH SET RESOURCE_MONITOR = EV_PIPELINE_MONITOR;

-- Account-level monitor
CREATE OR REPLACE RESOURCE MONITOR EV_ACCOUNT_MONITOR
  WITH CREDIT_QUOTA = 50
  FREQUENCY = MONTHLY
  START_TIMESTAMP = IMMEDIATELY
  TRIGGERS
    ON 75 PERCENT DO NOTIFY
    ON 90 PERCENT DO SUSPEND
    ON 100 PERCENT DO SUSPEND_IMMEDIATE;

ALTER ACCOUNT SET RESOURCE_MONITOR = EV_ACCOUNT_MONITOR;
