-- ============================================================
-- 08_COST_OBSERVABILITY.sql
-- Cost governance telemetry tables + refresh procedure + views
-- for AI explainability.
-- ============================================================

CREATE SCHEMA IF NOT EXISTS EV_PROJECT_DB.COST_GOVERNANCE;

USE SCHEMA EV_PROJECT_DB.COST_GOVERNANCE;

-- Snapshot of resource monitor status at each refresh.
CREATE OR REPLACE TABLE MONITOR_STATUS_SNAPSHOTS (
  SNAPSHOT_TS TIMESTAMP_LTZ,
  MONITOR_NAME VARCHAR,
  MONITOR_LEVEL VARCHAR,
  CREDIT_QUOTA NUMBER(18,6),
  USED_CREDITS NUMBER(18,6),
  REMAINING_CREDITS NUMBER(18,6),
  PCT_USED NUMBER(9,4),
  NOTIFY_PERCENT NUMBER(9,4),
  SUSPEND_PERCENT NUMBER(9,4),
  SUSPEND_IMMEDIATE_PERCENT NUMBER(9,4),
  OWNER VARCHAR,
  WAREHOUSES VARCHAR
);

-- Daily metering rollup for warehouse usage.
CREATE OR REPLACE TABLE WAREHOUSE_COST_DAILY (
  USAGE_DATE DATE,
  WAREHOUSE_NAME VARCHAR,
  CREDITS_USED_COMPUTE NUMBER(18,6),
  CREDITS_USED_CLOUD_SERVICES NUMBER(18,6),
  CREDITS_USED_TOTAL NUMBER(18,6),
  LAST_UPDATED_TS TIMESTAMP_LTZ
);

-- AI-ready fact table with projected end-of-cycle status.
CREATE OR REPLACE TABLE COST_SITUATION_FACT (
  SNAPSHOT_TS TIMESTAMP_LTZ,
  MONITOR_NAME VARCHAR,
  MONITOR_LEVEL VARCHAR,
  CREDIT_QUOTA NUMBER(18,6),
  USED_CREDITS NUMBER(18,6),
  REMAINING_CREDITS NUMBER(18,6),
  PCT_USED NUMBER(9,4),
  DAYS_LEFT_IN_CYCLE NUMBER(10,0),
  AVG_DAILY_CREDITS_7D NUMBER(18,6),
  PROJECTED_MONTH_END_CREDITS NUMBER(18,6),
  CURRENT_STATUS VARCHAR,
  PROJECTED_STATUS VARCHAR,
  NARRATIVE_HINT VARCHAR
);

CREATE OR REPLACE PROCEDURE SP_REFRESH_COST_OBSERVABILITY(LOOKBACK_DAYS NUMBER DEFAULT 30)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
  V_SNAPSHOT_TS TIMESTAMP_LTZ;
BEGIN
  V_SNAPSHOT_TS := CURRENT_TIMESTAMP();

  INSERT INTO EV_PROJECT_DB.COST_GOVERNANCE.MONITOR_STATUS_SNAPSHOTS
  SELECT
    :V_SNAPSHOT_TS,
    NAME AS MONITOR_NAME,
    IFF(WAREHOUSES IS NULL, 'ACCOUNT', 'WAREHOUSE') AS MONITOR_LEVEL,
    CREDIT_QUOTA,
    USED_CREDITS,
    REMAINING_CREDITS,
    IFF(CREDIT_QUOTA = 0, 0, (USED_CREDITS / CREDIT_QUOTA) * 100) AS PCT_USED,
    NOTIFY AS NOTIFY_PERCENT,
    SUSPEND AS SUSPEND_PERCENT,
    SUSPEND_IMMEDIATE AS SUSPEND_IMMEDIATE_PERCENT,
    OWNER,
    WAREHOUSES
  FROM SNOWFLAKE.ACCOUNT_USAGE.RESOURCE_MONITORS
  WHERE NAME IN ('EV_PIPELINE_MONITOR', 'EV_ACCOUNT_MONITOR');

  MERGE INTO EV_PROJECT_DB.COST_GOVERNANCE.WAREHOUSE_COST_DAILY tgt
  USING (
    SELECT
      DATE_TRUNC('DAY', START_TIME)::DATE AS USAGE_DATE,
      WAREHOUSE_NAME,
      SUM(CREDITS_USED_COMPUTE) AS CREDITS_USED_COMPUTE,
      SUM(CREDITS_USED_CLOUD_SERVICES) AS CREDITS_USED_CLOUD_SERVICES,
      SUM(CREDITS_USED) AS CREDITS_USED_TOTAL,
      CURRENT_TIMESTAMP() AS LAST_UPDATED_TS
    FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
    WHERE START_TIME >= DATEADD('DAY', -:LOOKBACK_DAYS, CURRENT_TIMESTAMP())
      AND WAREHOUSE_NAME IS NOT NULL
    GROUP BY 1, 2
  ) src
  ON tgt.USAGE_DATE = src.USAGE_DATE
     AND tgt.WAREHOUSE_NAME = src.WAREHOUSE_NAME
  WHEN MATCHED THEN UPDATE SET
    tgt.CREDITS_USED_COMPUTE = src.CREDITS_USED_COMPUTE,
    tgt.CREDITS_USED_CLOUD_SERVICES = src.CREDITS_USED_CLOUD_SERVICES,
    tgt.CREDITS_USED_TOTAL = src.CREDITS_USED_TOTAL,
    tgt.LAST_UPDATED_TS = src.LAST_UPDATED_TS
  WHEN NOT MATCHED THEN INSERT (
    USAGE_DATE,
    WAREHOUSE_NAME,
    CREDITS_USED_COMPUTE,
    CREDITS_USED_CLOUD_SERVICES,
    CREDITS_USED_TOTAL,
    LAST_UPDATED_TS
  ) VALUES (
    src.USAGE_DATE,
    src.WAREHOUSE_NAME,
    src.CREDITS_USED_COMPUTE,
    src.CREDITS_USED_CLOUD_SERVICES,
    src.CREDITS_USED_TOTAL,
    src.LAST_UPDATED_TS
  );

  INSERT INTO EV_PROJECT_DB.COST_GOVERNANCE.COST_SITUATION_FACT
  WITH latest_monitor AS (
    SELECT *
    FROM EV_PROJECT_DB.COST_GOVERNANCE.MONITOR_STATUS_SNAPSHOTS
    WHERE SNAPSHOT_TS = :V_SNAPSHOT_TS
  ),
  burn_rate AS (
    SELECT
      AVG(CREDITS_USED_TOTAL) AS AVG_DAILY_CREDITS_7D
    FROM EV_PROJECT_DB.COST_GOVERNANCE.WAREHOUSE_COST_DAILY
    WHERE USAGE_DATE >= DATEADD('DAY', -7, CURRENT_DATE())
      AND WAREHOUSE_NAME = 'COMPUTE_WH'
  ),
  horizon AS (
    SELECT DATEDIFF('DAY', CURRENT_DATE(), DATEADD('MONTH', 1, DATE_TRUNC('MONTH', CURRENT_DATE()))) AS DAYS_LEFT
  )
  SELECT
    :V_SNAPSHOT_TS AS SNAPSHOT_TS,
    lm.MONITOR_NAME,
    lm.MONITOR_LEVEL,
    lm.CREDIT_QUOTA,
    lm.USED_CREDITS,
    lm.REMAINING_CREDITS,
    lm.PCT_USED,
    h.DAYS_LEFT AS DAYS_LEFT_IN_CYCLE,
    COALESCE(br.AVG_DAILY_CREDITS_7D, 0) AS AVG_DAILY_CREDITS_7D,
    lm.USED_CREDITS + (COALESCE(br.AVG_DAILY_CREDITS_7D, 0) * h.DAYS_LEFT) AS PROJECTED_MONTH_END_CREDITS,
    CASE
      WHEN lm.PCT_USED >= lm.SUSPEND_IMMEDIATE_PERCENT THEN 'CRITICAL'
      WHEN lm.PCT_USED >= lm.SUSPEND_PERCENT THEN 'HIGH'
      WHEN lm.PCT_USED >= lm.NOTIFY_PERCENT THEN 'MEDIUM'
      ELSE 'LOW'
    END AS CURRENT_STATUS,
    CASE
      WHEN lm.CREDIT_QUOTA = 0 THEN 'UNKNOWN'
      WHEN ((lm.USED_CREDITS + (COALESCE(br.AVG_DAILY_CREDITS_7D, 0) * h.DAYS_LEFT)) / lm.CREDIT_QUOTA) * 100 >= lm.SUSPEND_IMMEDIATE_PERCENT THEN 'CRITICAL'
      WHEN ((lm.USED_CREDITS + (COALESCE(br.AVG_DAILY_CREDITS_7D, 0) * h.DAYS_LEFT)) / lm.CREDIT_QUOTA) * 100 >= lm.SUSPEND_PERCENT THEN 'HIGH'
      WHEN ((lm.USED_CREDITS + (COALESCE(br.AVG_DAILY_CREDITS_7D, 0) * h.DAYS_LEFT)) / lm.CREDIT_QUOTA) * 100 >= lm.NOTIFY_PERCENT THEN 'MEDIUM'
      ELSE 'LOW'
    END AS PROJECTED_STATUS,
    CASE
      WHEN lm.MONITOR_NAME = 'EV_PIPELINE_MONITOR' THEN 'Pipeline warehouse budget posture'
      WHEN lm.MONITOR_NAME = 'EV_ACCOUNT_MONITOR' THEN 'Account-wide budget posture'
      ELSE 'General monitor posture'
    END AS NARRATIVE_HINT
  FROM latest_monitor lm
  CROSS JOIN burn_rate br
  CROSS JOIN horizon h;

  RETURN 'OK: cost observability refresh completed';
END;
$$;

CREATE OR REPLACE VIEW V_COST_MONITOR_LATEST AS
SELECT *
FROM EV_PROJECT_DB.COST_GOVERNANCE.COST_SITUATION_FACT
QUALIFY ROW_NUMBER() OVER (PARTITION BY MONITOR_NAME ORDER BY SNAPSHOT_TS DESC) = 1;

CREATE OR REPLACE VIEW V_COST_DAILY_TREND AS
SELECT
  USAGE_DATE,
  WAREHOUSE_NAME,
  CREDITS_USED_COMPUTE,
  CREDITS_USED_CLOUD_SERVICES,
  CREDITS_USED_TOTAL,
  SUM(CREDITS_USED_TOTAL) OVER (PARTITION BY WAREHOUSE_NAME ORDER BY USAGE_DATE) AS CUMULATIVE_CREDITS
FROM EV_PROJECT_DB.COST_GOVERNANCE.WAREHOUSE_COST_DAILY;

CREATE OR REPLACE VIEW V_COST_AI_BRIEF AS
SELECT
  SNAPSHOT_TS,
  MONITOR_NAME,
  MONITOR_LEVEL,
  CURRENT_STATUS,
  PROJECTED_STATUS,
  ROUND(PCT_USED, 2) AS PCT_USED,
  ROUND(PROJECTED_MONTH_END_CREDITS, 4) AS PROJECTED_MONTH_END_CREDITS,
  ROUND(CREDIT_QUOTA, 4) AS CREDIT_QUOTA,
  ROUND(AVG_DAILY_CREDITS_7D, 4) AS AVG_DAILY_CREDITS_7D,
  DAYS_LEFT_IN_CYCLE,
  NARRATIVE_HINT,
  CASE
    WHEN PROJECTED_STATUS IN ('HIGH', 'CRITICAL') THEN 'Recommended action: reduce warehouse runtime or scale down compute usage.'
    ELSE 'Recommended action: current spend trajectory is within configured thresholds.'
  END AS RECOMMENDED_ACTION
FROM EV_PROJECT_DB.COST_GOVERNANCE.V_COST_MONITOR_LATEST;
