-- ============================================================
-- 02_DEMO_POSTGRESQL_SIMULATION.sql
-- Demo-only simulation of an external PostgreSQL normalized source
-- using existing JSON data already loaded in Snowflake.
--
-- Scope:
-- 1) Build normalized reference/core tables with IDs and codes
-- 2) Build a fact table at 1 row per JSON registration record
-- 3) Publish denormalized materialized views for analytics consumption
--
-- Important:
-- - This file is additive and does not replace existing product-ready CDC flow.
-- - Safe to re-run for demo refreshes (uses CREATE OR REPLACE).
-- ============================================================

USE DATABASE EV_PROJECT_DB;

CREATE SCHEMA IF NOT EXISTS REFERENCE;
CREATE SCHEMA IF NOT EXISTS CORE;
CREATE SCHEMA IF NOT EXISTS CONSUMPTION;

-- ------------------------------------------------------------
-- 1) Source flatten (from existing BRONZE raw JSON)
-- ------------------------------------------------------------
CREATE OR REPLACE TEMP TABLE TMP_EV_FLAT AS
SELECT
    f.value[8]::VARCHAR  AS VIN,
    f.value[13]::INT     AS MODEL_YEAR,
    f.value[14]::VARCHAR AS MAKE,
    f.value[15]::VARCHAR AS MODEL,
    f.value[16]::VARCHAR AS EV_TYPE,
    f.value[17]::VARCHAR AS CAFV_ELIGIBILITY,
    f.value[18]::INT     AS ELECTRIC_RANGE,
    f.value[19]::FLOAT   AS BASE_MSRP,
    f.value[20]::VARCHAR AS LEGISLATIVE_DISTRICT,
    f.value[21]::VARCHAR AS DOL_VEHICLE_ID,
    f.value[23]::VARCHAR AS ELECTRIC_UTILITY,
    f.value[25]::VARCHAR AS COUNTIES,
    r.SOURCE_FILE,
    r.LOAD_TIMESTAMP
FROM EV_PROJECT_DB.BRONZE.RAW_EV_DATA r,
     LATERAL FLATTEN(input => r.JSON_DATA:data) f
WHERE f.value[8] IS NOT NULL;

-- ------------------------------------------------------------
-- 2) Reference dimensions (IDs + business codes)
-- ------------------------------------------------------------
CREATE OR REPLACE TABLE EV_PROJECT_DB.REFERENCE.DIM_MAKE AS
SELECT 0 AS MAKE_ID, 'UNK' AS MAKE_CODE, 'UNKNOWN' AS MAKE_NAME
UNION ALL
SELECT
    ROW_NUMBER() OVER (ORDER BY MAKE_NAME) AS MAKE_ID,
    REGEXP_REPLACE(UPPER(TRIM(MAKE_NAME)), '[^A-Z0-9]+', '_') AS MAKE_CODE,
    MAKE_NAME
FROM (
    SELECT DISTINCT UPPER(TRIM(MAKE)) AS MAKE_NAME
    FROM TMP_EV_FLAT
    WHERE MAKE IS NOT NULL AND TRIM(MAKE) <> ''
);

CREATE OR REPLACE TABLE EV_PROJECT_DB.REFERENCE.DIM_MODEL AS
SELECT
    0 AS MODEL_ID,
    0 AS MAKE_ID,
    'UNK' AS MODEL_CODE,
    'UNKNOWN' AS MODEL_NAME
UNION ALL
SELECT
    ROW_NUMBER() OVER (ORDER BY MAKE_ID, MODEL_NAME) AS MODEL_ID,
    MAKE_ID,
    REGEXP_REPLACE(UPPER(TRIM(MODEL_NAME)), '[^A-Z0-9]+', '_') AS MODEL_CODE,
    MODEL_NAME
FROM (
    SELECT DISTINCT
        m.MAKE_ID,
        UPPER(TRIM(t.MODEL)) AS MODEL_NAME
    FROM TMP_EV_FLAT t
    JOIN EV_PROJECT_DB.REFERENCE.DIM_MAKE m
      ON UPPER(TRIM(t.MAKE)) = m.MAKE_NAME
    WHERE t.MODEL IS NOT NULL AND TRIM(t.MODEL) <> ''
);

CREATE OR REPLACE TABLE EV_PROJECT_DB.REFERENCE.DIM_EV_TYPE AS
SELECT 0 AS EV_TYPE_ID, 'UNK' AS EV_TYPE_CODE, 'UNKNOWN' AS EV_TYPE_NAME
UNION ALL
SELECT
    ROW_NUMBER() OVER (ORDER BY EV_TYPE_NAME) AS EV_TYPE_ID,
    REGEXP_REPLACE(UPPER(TRIM(EV_TYPE_NAME)), '[^A-Z0-9]+', '_') AS EV_TYPE_CODE,
    EV_TYPE_NAME
FROM (
    SELECT DISTINCT UPPER(TRIM(EV_TYPE)) AS EV_TYPE_NAME
    FROM TMP_EV_FLAT
    WHERE EV_TYPE IS NOT NULL AND TRIM(EV_TYPE) <> ''
);

CREATE OR REPLACE TABLE EV_PROJECT_DB.REFERENCE.DIM_CAFV AS
SELECT 0 AS CAFV_ID, 'UNK' AS CAFV_CODE, 'UNKNOWN' AS CAFV_NAME
UNION ALL
SELECT
    ROW_NUMBER() OVER (ORDER BY CAFV_NAME) AS CAFV_ID,
    REGEXP_REPLACE(UPPER(TRIM(CAFV_NAME)), '[^A-Z0-9]+', '_') AS CAFV_CODE,
    CAFV_NAME
FROM (
    SELECT DISTINCT UPPER(TRIM(CAFV_ELIGIBILITY)) AS CAFV_NAME
    FROM TMP_EV_FLAT
    WHERE CAFV_ELIGIBILITY IS NOT NULL AND TRIM(CAFV_ELIGIBILITY) <> ''
);

CREATE OR REPLACE TABLE EV_PROJECT_DB.REFERENCE.DIM_MODEL_YEAR AS
SELECT 0 AS MODEL_YEAR_ID, 'UNK' AS MODEL_YEAR_CODE, NULL::INT AS MODEL_YEAR
UNION ALL
SELECT
    ROW_NUMBER() OVER (ORDER BY MODEL_YEAR) AS MODEL_YEAR_ID,
    TO_VARCHAR(MODEL_YEAR) AS MODEL_YEAR_CODE,
    MODEL_YEAR
FROM (
    SELECT DISTINCT MODEL_YEAR
    FROM TMP_EV_FLAT
    WHERE MODEL_YEAR IS NOT NULL
);

CREATE OR REPLACE TABLE EV_PROJECT_DB.REFERENCE.DIM_UTILITY AS
SELECT 0 AS UTILITY_ID, 'UNK' AS UTILITY_CODE, 'UNKNOWN' AS UTILITY_NAME
UNION ALL
SELECT
    ROW_NUMBER() OVER (ORDER BY UTILITY_NAME) AS UTILITY_ID,
    REGEXP_REPLACE(UPPER(TRIM(UTILITY_NAME)), '[^A-Z0-9]+', '_') AS UTILITY_CODE,
    UTILITY_NAME
FROM (
    SELECT DISTINCT UPPER(TRIM(ELECTRIC_UTILITY)) AS UTILITY_NAME
    FROM TMP_EV_FLAT
    WHERE ELECTRIC_UTILITY IS NOT NULL AND TRIM(ELECTRIC_UTILITY) <> ''
);

CREATE OR REPLACE TABLE EV_PROJECT_DB.REFERENCE.DIM_LEGISLATIVE_DISTRICT AS
SELECT 0 AS LEGISLATIVE_DISTRICT_ID, 'UNK' AS LEGISLATIVE_DISTRICT_CODE, 'UNKNOWN' AS LEGISLATIVE_DISTRICT_NAME
UNION ALL
SELECT
    ROW_NUMBER() OVER (ORDER BY LEGISLATIVE_DISTRICT_NAME) AS LEGISLATIVE_DISTRICT_ID,
    REGEXP_REPLACE(UPPER(TRIM(LEGISLATIVE_DISTRICT_NAME)), '[^A-Z0-9]+', '_') AS LEGISLATIVE_DISTRICT_CODE,
    LEGISLATIVE_DISTRICT_NAME
FROM (
    SELECT DISTINCT UPPER(TRIM(LEGISLATIVE_DISTRICT)) AS LEGISLATIVE_DISTRICT_NAME
    FROM TMP_EV_FLAT
    WHERE LEGISLATIVE_DISTRICT IS NOT NULL AND TRIM(LEGISLATIVE_DISTRICT) <> ''
);

CREATE OR REPLACE TABLE EV_PROJECT_DB.REFERENCE.DIM_COUNTY AS
SELECT 0 AS COUNTY_ID, 'UNK' AS COUNTY_CODE, 'UNKNOWN' AS COUNTY_NAME
UNION ALL
SELECT
    ROW_NUMBER() OVER (ORDER BY COUNTY_NAME) AS COUNTY_ID,
    REGEXP_REPLACE(UPPER(TRIM(COUNTY_NAME)), '[^A-Z0-9]+', '_') AS COUNTY_CODE,
    COUNTY_NAME
FROM (
    SELECT DISTINCT UPPER(TRIM(COUNTIES)) AS COUNTY_NAME
    FROM TMP_EV_FLAT
    WHERE COUNTIES IS NOT NULL AND TRIM(COUNTIES) <> ''
);

-- ------------------------------------------------------------
-- 3) Core fact table (normalized; 1 row per JSON registration)
-- ------------------------------------------------------------
CREATE OR REPLACE TABLE EV_PROJECT_DB.CORE.FACT_EV_REGISTRATION_NORMALIZED (
    REGISTRATION_FACT_ID NUMBER(38,0),
    VIN VARCHAR,
    DOL_VEHICLE_ID VARCHAR,
    MAKE_ID NUMBER(38,0),
    MODEL_ID NUMBER(38,0),
    EV_TYPE_ID NUMBER(38,0),
    CAFV_ID NUMBER(38,0),
    MODEL_YEAR_ID NUMBER(38,0),
    UTILITY_ID NUMBER(38,0),
    LEGISLATIVE_DISTRICT_ID NUMBER(38,0),
    COUNTY_ID NUMBER(38,0),
    ELECTRIC_RANGE NUMBER(38,0),
    BASE_MSRP FLOAT,
    SOURCE_FILE VARCHAR,
    LOAD_TIMESTAMP TIMESTAMP_LTZ
);

INSERT OVERWRITE INTO EV_PROJECT_DB.CORE.FACT_EV_REGISTRATION_NORMALIZED
SELECT
    ROW_NUMBER() OVER (ORDER BY COALESCE(t.VIN, ''), COALESCE(t.DOL_VEHICLE_ID, ''), COALESCE(t.SOURCE_FILE, '')) AS REGISTRATION_FACT_ID,
    t.VIN,
    t.DOL_VEHICLE_ID,
    COALESCE(mk.MAKE_ID, 0) AS MAKE_ID,
    COALESCE(md.MODEL_ID, 0) AS MODEL_ID,
    COALESCE(et.EV_TYPE_ID, 0) AS EV_TYPE_ID,
    COALESCE(cf.CAFV_ID, 0) AS CAFV_ID,
    COALESCE(my.MODEL_YEAR_ID, 0) AS MODEL_YEAR_ID,
    COALESCE(ut.UTILITY_ID, 0) AS UTILITY_ID,
    COALESCE(ld.LEGISLATIVE_DISTRICT_ID, 0) AS LEGISLATIVE_DISTRICT_ID,
    COALESCE(ct.COUNTY_ID, 0) AS COUNTY_ID,
    t.ELECTRIC_RANGE,
    t.BASE_MSRP,
    t.SOURCE_FILE,
    t.LOAD_TIMESTAMP
FROM TMP_EV_FLAT t
LEFT JOIN EV_PROJECT_DB.REFERENCE.DIM_MAKE mk
  ON UPPER(TRIM(t.MAKE)) = mk.MAKE_NAME
LEFT JOIN EV_PROJECT_DB.REFERENCE.DIM_MODEL md
  ON UPPER(TRIM(t.MODEL)) = md.MODEL_NAME
 AND COALESCE(mk.MAKE_ID, 0) = md.MAKE_ID
LEFT JOIN EV_PROJECT_DB.REFERENCE.DIM_EV_TYPE et
  ON UPPER(TRIM(t.EV_TYPE)) = et.EV_TYPE_NAME
LEFT JOIN EV_PROJECT_DB.REFERENCE.DIM_CAFV cf
  ON UPPER(TRIM(t.CAFV_ELIGIBILITY)) = cf.CAFV_NAME
LEFT JOIN EV_PROJECT_DB.REFERENCE.DIM_MODEL_YEAR my
  ON t.MODEL_YEAR = my.MODEL_YEAR
LEFT JOIN EV_PROJECT_DB.REFERENCE.DIM_UTILITY ut
  ON UPPER(TRIM(t.ELECTRIC_UTILITY)) = ut.UTILITY_NAME
LEFT JOIN EV_PROJECT_DB.REFERENCE.DIM_LEGISLATIVE_DISTRICT ld
  ON UPPER(TRIM(t.LEGISLATIVE_DISTRICT)) = ld.LEGISLATIVE_DISTRICT_NAME
LEFT JOIN EV_PROJECT_DB.REFERENCE.DIM_COUNTY ct
  ON UPPER(TRIM(t.COUNTIES)) = ct.COUNTY_NAME;

-- Base denormalized table used by materialized views
CREATE OR REPLACE TABLE EV_PROJECT_DB.CONSUMPTION.EV_REGISTRATIONS_DENORM_BASE AS
SELECT
    f.REGISTRATION_FACT_ID,
    f.VIN,
    f.DOL_VEHICLE_ID,
    mk.MAKE_CODE,
    mk.MAKE_NAME,
    md.MODEL_CODE,
    md.MODEL_NAME,
    et.EV_TYPE_CODE,
    et.EV_TYPE_NAME,
    cf.CAFV_CODE,
    cf.CAFV_NAME,
    my.MODEL_YEAR,
    ut.UTILITY_CODE,
    ut.UTILITY_NAME,
    ld.LEGISLATIVE_DISTRICT_CODE,
    ld.LEGISLATIVE_DISTRICT_NAME,
    ct.COUNTY_CODE,
    ct.COUNTY_NAME,
    f.ELECTRIC_RANGE,
    f.BASE_MSRP,
    f.SOURCE_FILE,
    f.LOAD_TIMESTAMP
FROM EV_PROJECT_DB.CORE.FACT_EV_REGISTRATION_NORMALIZED f
LEFT JOIN EV_PROJECT_DB.REFERENCE.DIM_MAKE mk ON f.MAKE_ID = mk.MAKE_ID
LEFT JOIN EV_PROJECT_DB.REFERENCE.DIM_MODEL md ON f.MODEL_ID = md.MODEL_ID
LEFT JOIN EV_PROJECT_DB.REFERENCE.DIM_EV_TYPE et ON f.EV_TYPE_ID = et.EV_TYPE_ID
LEFT JOIN EV_PROJECT_DB.REFERENCE.DIM_CAFV cf ON f.CAFV_ID = cf.CAFV_ID
LEFT JOIN EV_PROJECT_DB.REFERENCE.DIM_MODEL_YEAR my ON f.MODEL_YEAR_ID = my.MODEL_YEAR_ID
LEFT JOIN EV_PROJECT_DB.REFERENCE.DIM_UTILITY ut ON f.UTILITY_ID = ut.UTILITY_ID
LEFT JOIN EV_PROJECT_DB.REFERENCE.DIM_LEGISLATIVE_DISTRICT ld ON f.LEGISLATIVE_DISTRICT_ID = ld.LEGISLATIVE_DISTRICT_ID
LEFT JOIN EV_PROJECT_DB.REFERENCE.DIM_COUNTY ct ON f.COUNTY_ID = ct.COUNTY_ID;

-- ------------------------------------------------------------
-- 4) Consumption materialized views (demo analytics surface)
-- ------------------------------------------------------------
CREATE OR REPLACE MATERIALIZED VIEW EV_PROJECT_DB.CONSUMPTION.MV_EV_REGISTRATIONS AS
SELECT
    REGISTRATION_FACT_ID,
    VIN,
    DOL_VEHICLE_ID,
    MAKE_CODE,
    MAKE_NAME,
    MODEL_CODE,
    MODEL_NAME,
    EV_TYPE_CODE,
    EV_TYPE_NAME,
    CAFV_CODE,
    CAFV_NAME,
    MODEL_YEAR,
    UTILITY_CODE,
    UTILITY_NAME,
    LEGISLATIVE_DISTRICT_CODE,
    LEGISLATIVE_DISTRICT_NAME,
    COUNTY_CODE,
    COUNTY_NAME,
    ELECTRIC_RANGE,
    BASE_MSRP,
    SOURCE_FILE,
    LOAD_TIMESTAMP
FROM EV_PROJECT_DB.CONSUMPTION.EV_REGISTRATIONS_DENORM_BASE;

CREATE OR REPLACE MATERIALIZED VIEW EV_PROJECT_DB.CONSUMPTION.MV_EV_MARKET_METRICS AS
SELECT
    MAKE_CODE,
    MAKE_NAME,
    EV_TYPE_CODE,
    EV_TYPE_NAME,
    MODEL_YEAR,
    COUNTY_CODE,
    COUNTY_NAME,
    COUNT(*) AS TOTAL_VEHICLES,
    AVG(ELECTRIC_RANGE) AS AVG_ELECTRIC_RANGE,
    MAX(BASE_MSRP) AS MAX_BASE_MSRP
FROM EV_PROJECT_DB.CONSUMPTION.EV_REGISTRATIONS_DENORM_BASE
GROUP BY
    MAKE_CODE,
    MAKE_NAME,
    EV_TYPE_CODE,
    EV_TYPE_NAME,
    MODEL_YEAR,
    COUNTY_CODE,
    COUNTY_NAME;

-- ------------------------------------------------------------
-- 5) Demo validation queries
-- ------------------------------------------------------------
-- SELECT COUNT(*) AS FACT_ROWS FROM EV_PROJECT_DB.CORE.FACT_EV_REGISTRATION_NORMALIZED;
-- SELECT COUNT(*) AS MV_ROWS FROM EV_PROJECT_DB.CONSUMPTION.MV_EV_REGISTRATIONS;
-- SELECT * FROM EV_PROJECT_DB.CONSUMPTION.MV_EV_MARKET_METRICS ORDER BY TOTAL_VEHICLES DESC LIMIT 20;
