-- ============================================================
-- 01_INFRASTRUCTURE.sql
-- Account-level objects: warehouse, storage integration,
-- notification integrations, external volume
-- ============================================================

-- Warehouse
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
  WAREHOUSE_SIZE = 'X-SMALL'
  AUTO_SUSPEND = 300
  AUTO_RESUME = TRUE;

-- Storage Integration (GCS)
CREATE OR REPLACE STORAGE INTEGRATION GCP_EV_STORAGE_INT
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'GCS'
  ENABLED = TRUE
  STORAGE_ALLOWED_LOCATIONS = ('gcs://ev-landing-zone-lordrivas/');

-- Notification Integration (Inbound — GCS Pub/Sub)
CREATE OR REPLACE NOTIFICATION INTEGRATION GCP_EV_PUBSUB_INT
  TYPE = QUEUE
  NOTIFICATION_PROVIDER = GCP_PUBSUB
  ENABLED = TRUE
  GCP_PUBSUB_SUBSCRIPTION_NAME = '<YOUR_PUBSUB_SUBSCRIPTION>';

-- Notification Integration (Outbound — Email for DQ Alerts)
CREATE OR REPLACE NOTIFICATION INTEGRATION EV_DQ_EMAIL_INT
  TYPE = EMAIL
  ENABLED = TRUE;

-- External Volume (GCS for Iceberg tables)
CREATE OR REPLACE EXTERNAL VOLUME GCP_ICEBERG_VOLUME
  STORAGE_LOCATIONS = (
    (
      NAME = 'gcs-iceberg'
      STORAGE_BASE_URL = 'gcs://<YOUR_ICEBERG_BUCKET>/'
    )
  )
  ALLOW_WRITES = TRUE;

-- Database
CREATE DATABASE IF NOT EXISTS EV_PROJECT_DB;

-- Schemas
CREATE SCHEMA IF NOT EXISTS EV_PROJECT_DB.BRONZE;
CREATE SCHEMA IF NOT EXISTS EV_PROJECT_DB.SILVER;
CREATE SCHEMA IF NOT EXISTS EV_PROJECT_DB.GOLD;
CREATE SCHEMA IF NOT EXISTS EV_PROJECT_DB.ICEBERG;
CREATE SCHEMA IF NOT EXISTS EV_PROJECT_DB.DBT_GOLD;
CREATE SCHEMA IF NOT EXISTS EV_PROJECT_DB.DATA_QUALITY;
CREATE SCHEMA IF NOT EXISTS EV_PROJECT_DB.SHARING;
