SELECT
    VIN,
    MAKE,
    MODEL,
    MODEL_YEAR,
    EV_TYPE,
    ELECTRIC_RANGE,
    BASE_MSRP,
    LEGISLATIVE_DISTRICT,
    DOL_VEHICLE_ID,
    VEHICLE_LOCATION,
    ELECTRIC_UTILITY,
    CENSUS_TRACT_2020,
    COUNTIES,
    SOURCE_FILE,
    CURRENT_TIMESTAMP() AS LOADED_AT
FROM {{ ref('stg_ev_registrations') }}
WHERE VIN IS NOT NULL
  AND MAKE IS NOT NULL
  AND MODEL IS NOT NULL
