SELECT
    MAKE,
    EV_TYPE,
    COUNT(VIN) AS TOTAL_VEHICLES,
    ROUND(AVG(ELECTRIC_RANGE), 1) AS AVG_RANGE,
    MAX(BASE_MSRP) AS MAX_MSRP,
    CURRENT_TIMESTAMP() AS LOAD_TIMESTAMP
FROM {{ ref('stg_ev_registrations') }}
WHERE MAKE IS NOT NULL
GROUP BY MAKE, EV_TYPE
