-- ================================================================
-- DATA QUALITY — Custom DMFs (EV_PROJECT_DB.DATA_QUALITY schema)
-- ================================================================

CREATE SCHEMA IF NOT EXISTS EV_PROJECT_DB.DATA_QUALITY;

-- Business Rule: Count rows where ELECTRIC_RANGE <= 0 or NULL
CREATE OR REPLACE DATA METRIC FUNCTION EV_PROJECT_DB.DATA_QUALITY.INVALID_ELECTRIC_RANGE(
  arg_t TABLE(arg_c1 NUMBER)
)
RETURNS NUMBER
AS
$$
  SELECT COUNT(*) FROM arg_t WHERE arg_c1 <= 0 OR arg_c1 IS NULL
$$;

-- Business Rule: Count rows where BASE_MSRP < 0
CREATE OR REPLACE DATA METRIC FUNCTION EV_PROJECT_DB.DATA_QUALITY.NEGATIVE_MSRP(
  arg_t TABLE(arg_c1 FLOAT)
)
RETURNS NUMBER
AS
$$
  SELECT COUNT(*) FROM arg_t WHERE arg_c1 < 0
$$;

-- Referential Integrity: Count MAKEs in silver not found in DIM_MANUFACTURERS
CREATE OR REPLACE DATA METRIC FUNCTION EV_PROJECT_DB.DATA_QUALITY.ORPHAN_MAKE_CHECK(
  arg_t1 TABLE(arg_c1 VARCHAR),
  arg_t2 TABLE(arg_c2 VARCHAR)
)
RETURNS NUMBER
AS
$$
  SELECT COUNT(*) FROM arg_t1
  WHERE arg_c1 NOT IN (SELECT arg_c2 FROM arg_t2)
$$;

-- ================================================================
-- DATA QUALITY — Attach DMFs to BRONZE.RAW_EV_DATA
-- Schedule: Every 30 minutes
-- ================================================================

ALTER TABLE EV_PROJECT_DB.BRONZE.RAW_EV_DATA SET DATA_METRIC_SCHEDULE = '30 MINUTE';

ALTER TABLE EV_PROJECT_DB.BRONZE.RAW_EV_DATA
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON ();
ALTER TABLE EV_PROJECT_DB.BRONZE.RAW_EV_DATA
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.FRESHNESS ON (LOAD_TIMESTAMP);
ALTER TABLE EV_PROJECT_DB.BRONZE.RAW_EV_DATA
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (SOURCE_FILE);

-- ================================================================
-- DATA QUALITY — Attach DMFs to SILVER.CLEAN_EV_DATA_DT
-- Schedule: Trigger on changes (event-driven)
-- ================================================================

ALTER TABLE EV_PROJECT_DB.SILVER.CLEAN_EV_DATA_DT SET DATA_METRIC_SCHEDULE = 'TRIGGER_ON_CHANGES';

ALTER TABLE EV_PROJECT_DB.SILVER.CLEAN_EV_DATA_DT
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON ();
ALTER TABLE EV_PROJECT_DB.SILVER.CLEAN_EV_DATA_DT
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (VIN);
ALTER TABLE EV_PROJECT_DB.SILVER.CLEAN_EV_DATA_DT
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (MAKE);
ALTER TABLE EV_PROJECT_DB.SILVER.CLEAN_EV_DATA_DT
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (MODEL);
ALTER TABLE EV_PROJECT_DB.SILVER.CLEAN_EV_DATA_DT
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (VIN);
ALTER TABLE EV_PROJECT_DB.SILVER.CLEAN_EV_DATA_DT
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (DOL_VEHICLE_ID);
ALTER TABLE EV_PROJECT_DB.SILVER.CLEAN_EV_DATA_DT
  ADD DATA METRIC FUNCTION EV_PROJECT_DB.DATA_QUALITY.INVALID_ELECTRIC_RANGE ON (ELECTRIC_RANGE);
ALTER TABLE EV_PROJECT_DB.SILVER.CLEAN_EV_DATA_DT
  ADD DATA METRIC FUNCTION EV_PROJECT_DB.DATA_QUALITY.NEGATIVE_MSRP ON (BASE_MSRP);
ALTER TABLE EV_PROJECT_DB.SILVER.CLEAN_EV_DATA_DT
  ADD DATA METRIC FUNCTION EV_PROJECT_DB.DATA_QUALITY.ORPHAN_MAKE_CHECK
    ON (MAKE, TABLE(EV_PROJECT_DB.GOLD.DIM_MANUFACTURERS_GOLD(MANUFACTURER_NAME)));

-- ================================================================
-- DATA QUALITY — Attach DMFs to GOLD.FACT_EV_MARKET_METRICS
-- Schedule: Trigger on changes (event-driven)
-- ================================================================

ALTER ICEBERG TABLE EV_PROJECT_DB.GOLD.FACT_EV_MARKET_METRICS SET DATA_METRIC_SCHEDULE = 'TRIGGER_ON_CHANGES';

ALTER TABLE EV_PROJECT_DB.GOLD.FACT_EV_MARKET_METRICS
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON ();
ALTER TABLE EV_PROJECT_DB.GOLD.FACT_EV_MARKET_METRICS
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.FRESHNESS ON (LOAD_TIMESTAMP);
ALTER TABLE EV_PROJECT_DB.GOLD.FACT_EV_MARKET_METRICS
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (MAKE);
ALTER TABLE EV_PROJECT_DB.GOLD.FACT_EV_MARKET_METRICS
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.AVG ON (TOTAL_VEHICLES);
ALTER TABLE EV_PROJECT_DB.GOLD.FACT_EV_MARKET_METRICS
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.MIN ON (AVG_RANGE);
ALTER TABLE EV_PROJECT_DB.GOLD.FACT_EV_MARKET_METRICS
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.MAX ON (AVG_RANGE);