-- ================================================================
-- DATA LINEAGE & AUDITABILITY
-- ================================================================

-- Pipeline lineage: tracks which objects wrote to which targets (last 14 days)
CREATE OR REPLACE VIEW EV_PROJECT_DB.DATA_QUALITY.V_PIPELINE_LINEAGE AS
SELECT
  DIRECTSOURCES.VALUE:"objectDomain"::STRING  AS SOURCE_TYPE,
  DIRECTSOURCES.VALUE:"objectName"::STRING     AS SOURCE_OBJECT,
  OBJECTS_MODIFIED.VALUE:"objectDomain"::STRING AS TARGET_TYPE,
  OBJECTS_MODIFIED.VALUE:"objectName"::STRING   AS TARGET_OBJECT,
  OBJECTS_MODIFIED.VALUE:"columns"              AS COLUMNS_MODIFIED,
  AH.USER_NAME,
  AH.QUERY_ID,
  AH.QUERY_START_TIME
FROM SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY AH,
  LATERAL FLATTEN(input => AH.OBJECTS_MODIFIED) OBJECTS_MODIFIED,
  LATERAL FLATTEN(input => OBJECTS_MODIFIED.VALUE:"directSources") DIRECTSOURCES
WHERE OBJECTS_MODIFIED.VALUE:"objectDomain"::STRING IN ('Table', 'Dynamic Table')
  AND (
    OBJECTS_MODIFIED.VALUE:"objectName"::STRING ILIKE '%EV_PROJECT_DB%'
    OR DIRECTSOURCES.VALUE:"objectName"::STRING ILIKE '%EV_PROJECT_DB%'
  )
  AND AH.QUERY_START_TIME >= DATEADD('day', -14, CURRENT_TIMESTAMP());

-- DQ audit: all DMF measurement results for EV_PROJECT_DB
CREATE OR REPLACE VIEW EV_PROJECT_DB.DATA_QUALITY.V_DQ_AUDIT AS
SELECT
  MEASUREMENT_TIME,
  TABLE_SCHEMA,
  TABLE_NAME,
  METRIC_DATABASE || '.' || METRIC_SCHEMA || '.' || METRIC_NAME AS DMF_NAME,
  ARGUMENT_NAMES,
  VALUE AS METRIC_VALUE,
  SCHEDULED_TIME,
  CHANGE_COMMIT_TIME
FROM SNOWFLAKE.LOCAL.DATA_QUALITY_MONITORING_RESULTS
WHERE TABLE_DATABASE = 'EV_PROJECT_DB';