-- ================================================================
-- ERROR HANDLING — Tables, Streams, Detection & Notification
-- ================================================================

-- Error rows table: captures all rows with data quality violations
CREATE OR REPLACE TABLE EV_PROJECT_DB.DATA_QUALITY.ERROR_ROWS (
    ERROR_ID NUMBER AUTOINCREMENT,
    DETECTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_LAYER VARCHAR,
    SOURCE_TABLE VARCHAR,
    ERROR_TYPE VARCHAR,
    ERROR_DESCRIPTION VARCHAR,
    VIN VARCHAR,
    MAKE VARCHAR,
    MODEL VARCHAR,
    MODEL_YEAR NUMBER,
    EV_TYPE VARCHAR,
    ELECTRIC_RANGE NUMBER,
    BASE_MSRP FLOAT,
    DOL_VEHICLE_ID VARCHAR,
    SOURCE_FILE VARCHAR,
    RAW_RECORD VARIANT
);

-- Duplicate rows table: tracks VINs with multiple occurrences in bronze
CREATE OR REPLACE TABLE EV_PROJECT_DB.DATA_QUALITY.DUPLICATE_ROWS (
    DUPLICATE_ID NUMBER AUTOINCREMENT,
    DETECTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    VIN VARCHAR,
    OCCURRENCE_COUNT NUMBER,
    MAKE VARCHAR,
    MODEL VARCHAR,
    SOURCE_FILES ARRAY
);

-- Streams on error tables (trigger notifications on new errors)
CREATE OR REPLACE STREAM EV_PROJECT_DB.DATA_QUALITY.ERROR_ROWS_STREAM
  ON TABLE EV_PROJECT_DB.DATA_QUALITY.ERROR_ROWS
  SHOW_INITIAL_ROWS = FALSE;

CREATE OR REPLACE STREAM EV_PROJECT_DB.DATA_QUALITY.DUPLICATE_ROWS_STREAM
  ON TABLE EV_PROJECT_DB.DATA_QUALITY.DUPLICATE_ROWS
  SHOW_INITIAL_ROWS = FALSE;

-- SP: Scans all layers for errors and populates error tables
CREATE OR REPLACE PROCEDURE EV_PROJECT_DB.DATA_QUALITY.SP_DETECT_ERRORS()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
BEGIN
    INSERT INTO EV_PROJECT_DB.DATA_QUALITY.DUPLICATE_ROWS
        (VIN, OCCURRENCE_COUNT, MAKE, MODEL, SOURCE_FILES)
    SELECT
        f.value[8]::VARCHAR AS VIN,
        COUNT(*) AS OCCURRENCE_COUNT,
        MAX(f.value[14]::VARCHAR) AS MAKE,
        MAX(f.value[15]::VARCHAR) AS MODEL,
        ARRAY_UNIQUE_AGG(SOURCE_FILE) AS SOURCE_FILES
    FROM EV_PROJECT_DB.BRONZE.RAW_EV_DATA,
        LATERAL FLATTEN(input => JSON_DATA:data) f
    WHERE f.value[8] IS NOT NULL
    GROUP BY f.value[8]::VARCHAR
    HAVING COUNT(*) > 1
      AND VIN NOT IN (SELECT VIN FROM EV_PROJECT_DB.DATA_QUALITY.DUPLICATE_ROWS);

    INSERT INTO EV_PROJECT_DB.DATA_QUALITY.ERROR_ROWS
        (SOURCE_LAYER, SOURCE_TABLE, ERROR_TYPE, ERROR_DESCRIPTION,
         MAKE, MODEL, EV_TYPE, SOURCE_FILE, RAW_RECORD)
    SELECT
        'BRONZE', 'RAW_EV_DATA', 'NULL_VIN', 'VIN is null — rejected from silver',
        f.value[14]::VARCHAR, f.value[15]::VARCHAR, f.value[16]::VARCHAR,
        SOURCE_FILE, f.value
    FROM EV_PROJECT_DB.BRONZE.RAW_EV_DATA,
        LATERAL FLATTEN(input => JSON_DATA:data) f
    WHERE f.value[8] IS NULL
      AND f.value::VARCHAR NOT IN (
        SELECT RAW_RECORD::VARCHAR FROM EV_PROJECT_DB.DATA_QUALITY.ERROR_ROWS WHERE ERROR_TYPE = 'NULL_VIN'
      );

    INSERT INTO EV_PROJECT_DB.DATA_QUALITY.ERROR_ROWS
        (SOURCE_LAYER, SOURCE_TABLE, ERROR_TYPE, ERROR_DESCRIPTION,
         VIN, MAKE, MODEL, ELECTRIC_RANGE, SOURCE_FILE)
    SELECT 'SILVER', 'CLEAN_EV_DATA_DT', 'INVALID_RANGE', 'Electric range <= 0',
        VIN, MAKE, MODEL, ELECTRIC_RANGE, SOURCE_FILE
    FROM EV_PROJECT_DB.SILVER.CLEAN_EV_DATA_DT
    WHERE ELECTRIC_RANGE <= 0
      AND VIN NOT IN (SELECT VIN FROM EV_PROJECT_DB.DATA_QUALITY.ERROR_ROWS WHERE ERROR_TYPE = 'INVALID_RANGE' AND VIN IS NOT NULL);

    INSERT INTO EV_PROJECT_DB.DATA_QUALITY.ERROR_ROWS
        (SOURCE_LAYER, SOURCE_TABLE, ERROR_TYPE, ERROR_DESCRIPTION,
         VIN, MAKE, MODEL, BASE_MSRP, SOURCE_FILE)
    SELECT 'SILVER', 'CLEAN_EV_DATA_DT', 'NEGATIVE_MSRP', 'BASE_MSRP < 0',
        VIN, MAKE, MODEL, BASE_MSRP, SOURCE_FILE
    FROM EV_PROJECT_DB.SILVER.CLEAN_EV_DATA_DT
    WHERE BASE_MSRP < 0
      AND VIN NOT IN (SELECT VIN FROM EV_PROJECT_DB.DATA_QUALITY.ERROR_ROWS WHERE ERROR_TYPE = 'NEGATIVE_MSRP' AND VIN IS NOT NULL);

    INSERT INTO EV_PROJECT_DB.DATA_QUALITY.ERROR_ROWS
        (SOURCE_LAYER, SOURCE_TABLE, ERROR_TYPE, ERROR_DESCRIPTION,
         VIN, MAKE, MODEL, SOURCE_FILE)
    SELECT 'SILVER', 'CLEAN_EV_DATA_DT', 'ORPHAN_MAKE', 'MAKE not found in DIM_MANUFACTURERS_GOLD',
        VIN, MAKE, MODEL, SOURCE_FILE
    FROM EV_PROJECT_DB.SILVER.CLEAN_EV_DATA_DT
    WHERE MAKE NOT IN (SELECT MANUFACTURER_NAME FROM EV_PROJECT_DB.GOLD.DIM_MANUFACTURERS_GOLD)
      AND VIN NOT IN (SELECT VIN FROM EV_PROJECT_DB.DATA_QUALITY.ERROR_ROWS WHERE ERROR_TYPE = 'ORPHAN_MAKE' AND VIN IS NOT NULL);

    INSERT INTO EV_PROJECT_DB.DATA_QUALITY.ERROR_ROWS
        (SOURCE_LAYER, SOURCE_TABLE, ERROR_TYPE, ERROR_DESCRIPTION,
         VIN, MAKE, MODEL, SOURCE_FILE)
    SELECT 'SILVER', 'CLEAN_EV_DATA_DT', 'NULL_CRITICAL_FIELD',
        CASE WHEN MAKE IS NULL THEN 'MAKE is null' ELSE 'MODEL is null' END,
        VIN, MAKE, MODEL, SOURCE_FILE
    FROM EV_PROJECT_DB.SILVER.CLEAN_EV_DATA_DT
    WHERE (MAKE IS NULL OR MODEL IS NULL)
      AND VIN NOT IN (SELECT VIN FROM EV_PROJECT_DB.DATA_QUALITY.ERROR_ROWS WHERE ERROR_TYPE = 'NULL_CRITICAL_FIELD' AND VIN IS NOT NULL);

    RETURN 'Error detection complete';
END;
$$;

-- Email notification integration
CREATE OR REPLACE NOTIFICATION INTEGRATION EV_DQ_EMAIL_INT
  TYPE = EMAIL
  ENABLED = TRUE
  ALLOWED_RECIPIENTS = ('lordrivas@gmail.com');

-- SP: Sends email alert when new errors are detected
CREATE OR REPLACE PROCEDURE EV_PROJECT_DB.DATA_QUALITY.SP_NOTIFY_ERRORS()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    new_errors NUMBER;
    new_dupes NUMBER;
    email_body VARCHAR;
BEGIN
    SELECT COUNT(*) INTO :new_errors
    FROM EV_PROJECT_DB.DATA_QUALITY.ERROR_ROWS_STREAM WHERE METADATA$ACTION = 'INSERT';

    SELECT COUNT(*) INTO :new_dupes
    FROM EV_PROJECT_DB.DATA_QUALITY.DUPLICATE_ROWS_STREAM WHERE METADATA$ACTION = 'INSERT';

    IF (:new_errors > 0 OR :new_dupes > 0) THEN
        email_body := 'EV Pipeline Data Quality Alert\n\n'
            || 'New error rows detected: ' || :new_errors || '\n'
            || 'New duplicate VINs detected: ' || :new_dupes || '\n\n'
            || 'Review: SELECT * FROM EV_PROJECT_DB.DATA_QUALITY.ERROR_ROWS ORDER BY DETECTED_AT DESC;';

        CALL SYSTEM$SEND_EMAIL('EV_DQ_EMAIL_INT', 'lordrivas@gmail.com',
            'EV Pipeline — Data Quality Alert', :email_body);

        RETURN 'Notification sent: ' || :new_errors || ' errors, ' || :new_dupes || ' duplicates';
    ELSE
        RETURN 'No new errors detected';
    END IF;
END;
$$;

-- Task DAG: Event-driven error detection chained to ingestion
-- TSK_INGEST_EV_DATA (root) → TSK_ERROR_DETECTION → TSK_ERROR_NOTIFICATION
-- Errors are detected immediately after new data is ingested, not on a fixed schedule.

CREATE OR REPLACE TASK EV_PROJECT_DB.BRONZE.TSK_ERROR_DETECTION
  WAREHOUSE = COMPUTE_WH
  AFTER EV_PROJECT_DB.BRONZE.TSK_INGEST_EV_DATA
AS
  CALL EV_PROJECT_DB.DATA_QUALITY.SP_DETECT_ERRORS();

CREATE OR REPLACE TASK EV_PROJECT_DB.BRONZE.TSK_ERROR_NOTIFICATION
  WAREHOUSE = COMPUTE_WH
  AFTER EV_PROJECT_DB.BRONZE.TSK_ERROR_DETECTION
AS
  CALL EV_PROJECT_DB.DATA_QUALITY.SP_NOTIFY_ERRORS();

-- Resume children first, then root
ALTER TASK EV_PROJECT_DB.BRONZE.TSK_ERROR_NOTIFICATION RESUME;
ALTER TASK EV_PROJECT_DB.BRONZE.TSK_ERROR_DETECTION RESUME;
-- (Root task TSK_INGEST_EV_DATA is already resumed in the BRONZE section above)