-- ============================================================
-- 07_SHARING.sql
-- Governed data sharing: secure views over Iceberg tables,
-- outbound share for cross-account access
-- ============================================================

USE SCHEMA EV_PROJECT_DB.SHARING;

-- Secure view — market metrics (from Iceberg)
CREATE OR REPLACE SECURE VIEW SV_FACT_EV_MARKET_METRICS AS
SELECT * FROM EV_PROJECT_DB.ICEBERG.FACT_EV_MARKET_METRICS;

-- Secure view — manufacturer dimension (from Iceberg)
CREATE OR REPLACE SECURE VIEW SV_DIM_MANUFACTURERS AS
SELECT * FROM EV_PROJECT_DB.ICEBERG.DIM_MANUFACTURERS_GOLD;

-- Secure view — data quality summary (transparency for consumers)
CREATE OR REPLACE SECURE VIEW SV_DATA_QUALITY_SUMMARY AS
SELECT SOURCE_LAYER, ERROR_TYPE, TOTAL_ERRORS, ERRORS_LAST_24H, RECONCILIATION_STATUS
FROM EV_PROJECT_DB.DATA_QUALITY.V_DQ_DASHBOARD;

-- Outbound share
CREATE OR REPLACE SHARE EV_MARKET_DATA_SHARE
  COMMENT = 'EV market metrics, manufacturer dimensions, and data quality summary';

GRANT USAGE ON DATABASE EV_PROJECT_DB TO SHARE EV_MARKET_DATA_SHARE;
GRANT USAGE ON SCHEMA EV_PROJECT_DB.SHARING TO SHARE EV_MARKET_DATA_SHARE;
GRANT SELECT ON VIEW EV_PROJECT_DB.SHARING.SV_FACT_EV_MARKET_METRICS TO SHARE EV_MARKET_DATA_SHARE;
GRANT SELECT ON VIEW EV_PROJECT_DB.SHARING.SV_DIM_MANUFACTURERS TO SHARE EV_MARKET_DATA_SHARE;
GRANT SELECT ON VIEW EV_PROJECT_DB.SHARING.SV_DATA_QUALITY_SUMMARY TO SHARE EV_MARKET_DATA_SHARE;
