-- ================================================================
-- ANALYST DASHBOARD VIEWS
-- ================================================================

-- Main DQ dashboard: error summary + reconciliation status
CREATE OR REPLACE VIEW EV_PROJECT_DB.DATA_QUALITY.V_DQ_DASHBOARD AS
WITH error_summary AS (
    SELECT
        ERROR_TYPE, SOURCE_LAYER,
        COUNT(*) AS TOTAL_ERRORS,
        COUNT(CASE WHEN DETECTED_AT >= DATEADD('hour', -24, CURRENT_TIMESTAMP()) THEN 1 END) AS ERRORS_LAST_24H,
        COUNT(CASE WHEN DETECTED_AT >= DATEADD('hour', -1, CURRENT_TIMESTAMP()) THEN 1 END) AS ERRORS_LAST_1H,
        MIN(DETECTED_AT) AS FIRST_SEEN,
        MAX(DETECTED_AT) AS LAST_SEEN
    FROM EV_PROJECT_DB.DATA_QUALITY.ERROR_ROWS
    GROUP BY ERROR_TYPE, SOURCE_LAYER
),
duplicate_summary AS (
    SELECT COUNT(*) AS TOTAL_DUPLICATE_VINS, SUM(OCCURRENCE_COUNT) AS TOTAL_DUPLICATE_ROWS,
        COUNT(CASE WHEN DETECTED_AT >= DATEADD('hour', -24, CURRENT_TIMESTAMP()) THEN 1 END) AS DUPES_LAST_24H
    FROM EV_PROJECT_DB.DATA_QUALITY.DUPLICATE_ROWS
),
reconciliation AS (
    SELECT * FROM EV_PROJECT_DB.DATA_QUALITY.V_ROW_COUNT_RECONCILIATION
)
SELECT
    e.SOURCE_LAYER, e.ERROR_TYPE, e.TOTAL_ERRORS,
    e.ERRORS_LAST_24H, e.ERRORS_LAST_1H, e.FIRST_SEEN, e.LAST_SEEN,
    d.TOTAL_DUPLICATE_VINS, d.TOTAL_DUPLICATE_ROWS, d.DUPES_LAST_24H,
    r.BRONZE_RAW_ROWS, r.SILVER_ROWS, r.GOLD_TOTAL_VEHICLES,
    r.BRONZE_TO_SILVER_DRIFT, r.SILVER_TO_GOLD_DRIFT,
    r.STATUS AS RECONCILIATION_STATUS
FROM error_summary e
CROSS JOIN duplicate_summary d
CROSS JOIN reconciliation r;

-- Error trend: hourly error counts by type (for time-series charts)
CREATE OR REPLACE VIEW EV_PROJECT_DB.DATA_QUALITY.V_ERROR_TREND AS
SELECT
    DATE_TRUNC('hour', DETECTED_AT) AS HOUR,
    ERROR_TYPE, SOURCE_LAYER,
    COUNT(*) AS ERROR_COUNT
FROM EV_PROJECT_DB.DATA_QUALITY.ERROR_ROWS
GROUP BY DATE_TRUNC('hour', DETECTED_AT), ERROR_TYPE, SOURCE_LAYER;

-- Top offenders: MAKEs with the most quality issues
CREATE OR REPLACE VIEW EV_PROJECT_DB.DATA_QUALITY.V_TOP_OFFENDERS AS
SELECT
    MAKE, COUNT(*) AS TOTAL_ERRORS,
    COUNT(DISTINCT ERROR_TYPE) AS DISTINCT_ERROR_TYPES,
    ARRAY_UNIQUE_AGG(ERROR_TYPE) AS ERROR_TYPES,
    COUNT(CASE WHEN ERROR_TYPE = 'INVALID_RANGE' THEN 1 END) AS INVALID_RANGE_COUNT,
    COUNT(CASE WHEN ERROR_TYPE = 'ORPHAN_MAKE' THEN 1 END) AS ORPHAN_MAKE_COUNT,
    COUNT(CASE WHEN ERROR_TYPE = 'NULL_CRITICAL_FIELD' THEN 1 END) AS NULL_FIELD_COUNT
FROM EV_PROJECT_DB.DATA_QUALITY.ERROR_ROWS
WHERE MAKE IS NOT NULL
GROUP BY MAKE
ORDER BY TOTAL_ERRORS DESC;

-- ================================================================
-- SEMANTIC MODEL — Cortex Analyst (staged YAML)
-- ================================================================

CREATE STAGE IF NOT EXISTS EV_PROJECT_DB.GOLD.SEMANTIC_MODELS;
-- Semantic model file: @EV_PROJECT_DB.GOLD.SEMANTIC_MODELS/ev_semantic_model.yaml