ev_pipeline:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT', 'jzfcdcp-vn23603') }}"
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
      role: "{{ env_var('DBT_SNOWFLAKE_ROLE', 'ACCOUNTADMIN') }}"
      database: "{{ env_var('DBT_SNOWFLAKE_DATABASE', 'EV_PROJECT_DB') }}"
      warehouse: "{{ env_var('DBT_SNOWFLAKE_WAREHOUSE', 'COMPUTE_WH') }}"
      schema: "{{ env_var('DBT_SNOWFLAKE_SCHEMA', 'DBT_GOLD') }}"
      threads: 4
      password: "{{ env_var('DBT_SNOWFLAKE_PASSWORD', '') }}"
      client_session_keep_alive: false
