-- ============================================================
-- 02_DEMO_KPI_QUERIES.sql
-- Demo query pack for denormalized analytics materialized views.
--
-- Important:
-- - Azure ingestion remains the source path:
--   Azure Blob -> BRONZE.RAW_EV_DATA -> demo normalization script
-- - Run 04b_external_data_integration/02_demo_postgresql_simulation.sql
--   after new Azure ingestions to refresh demo-normalized outputs.
-- ============================================================

USE DATABASE EV_PROJECT_DB;
USE SCHEMA CONSUMPTION;

-- 1) Top 15 manufacturers by registrations
SELECT
  MAKE_NAME,
  SUM(TOTAL_VEHICLES) AS TOTAL_REGISTRATIONS
FROM EV_PROJECT_DB.CONSUMPTION.MV_EV_MARKET_METRICS
GROUP BY MAKE_NAME
ORDER BY TOTAL_REGISTRATIONS DESC
LIMIT 15;

-- 2) BEV vs PHEV total distribution
SELECT
  EV_TYPE_NAME,
  SUM(TOTAL_VEHICLES) AS TOTAL_REGISTRATIONS
FROM EV_PROJECT_DB.CONSUMPTION.MV_EV_MARKET_METRICS
GROUP BY EV_TYPE_NAME
ORDER BY TOTAL_REGISTRATIONS DESC;

-- 3) Top 20 make/model combinations by registrations
SELECT
  MAKE_NAME,
  MODEL_NAME,
  COUNT(*) AS TOTAL_REGISTRATIONS
FROM EV_PROJECT_DB.CONSUMPTION.MV_EV_REGISTRATIONS
GROUP BY MAKE_NAME, MODEL_NAME
ORDER BY TOTAL_REGISTRATIONS DESC
LIMIT 20;

-- 4) County ranking by total EV registrations
SELECT
  COUNTY_NAME,
  COUNT(*) AS TOTAL_REGISTRATIONS
FROM EV_PROJECT_DB.CONSUMPTION.MV_EV_REGISTRATIONS
GROUP BY COUNTY_NAME
ORDER BY TOTAL_REGISTRATIONS DESC
LIMIT 20;

-- 5) Manufacturer EV-type mix (%)
WITH make_mix AS (
  SELECT
    MAKE_NAME,
    EV_TYPE_NAME,
    COUNT(*) AS REGS
  FROM EV_PROJECT_DB.CONSUMPTION.MV_EV_REGISTRATIONS
  GROUP BY MAKE_NAME, EV_TYPE_NAME
), make_totals AS (
  SELECT
    MAKE_NAME,
    SUM(REGS) AS TOTAL_REGS
  FROM make_mix
  GROUP BY MAKE_NAME
)
SELECT
  m.MAKE_NAME,
  m.EV_TYPE_NAME,
  m.REGS,
  ROUND((m.REGS * 100.0) / NULLIF(t.TOTAL_REGS, 0), 2) AS MIX_PCT
FROM make_mix m
JOIN make_totals t
  ON m.MAKE_NAME = t.MAKE_NAME
ORDER BY t.TOTAL_REGS DESC, MIX_PCT DESC
LIMIT 50;

-- 6) Average electric range by manufacturer (min 100 vehicles)
SELECT
  MAKE_NAME,
  ROUND(AVG(ELECTRIC_RANGE), 2) AS AVG_ELECTRIC_RANGE,
  COUNT(*) AS VEHICLE_COUNT
FROM EV_PROJECT_DB.CONSUMPTION.MV_EV_REGISTRATIONS
WHERE ELECTRIC_RANGE IS NOT NULL
GROUP BY MAKE_NAME
HAVING COUNT(*) >= 100
ORDER BY AVG_ELECTRIC_RANGE DESC
LIMIT 25;

-- 7) CAFV eligibility distribution
SELECT
  CAFV_NAME,
  COUNT(*) AS TOTAL_REGISTRATIONS
FROM EV_PROJECT_DB.CONSUMPTION.MV_EV_REGISTRATIONS
GROUP BY CAFV_NAME
ORDER BY TOTAL_REGISTRATIONS DESC;

-- 8) Model year trend by EV type
SELECT
  MODEL_YEAR,
  EV_TYPE_NAME,
  COUNT(*) AS TOTAL_REGISTRATIONS
FROM EV_PROJECT_DB.CONSUMPTION.MV_EV_REGISTRATIONS
WHERE MODEL_YEAR IS NOT NULL
GROUP BY MODEL_YEAR, EV_TYPE_NAME
ORDER BY MODEL_YEAR, EV_TYPE_NAME;

-- 9) Utility coverage and EV counts
SELECT
  UTILITY_NAME,
  COUNT(*) AS TOTAL_REGISTRATIONS,
  COUNT(DISTINCT COUNTY_NAME) AS COVERED_COUNTIES
FROM EV_PROJECT_DB.CONSUMPTION.MV_EV_REGISTRATIONS
GROUP BY UTILITY_NAME
ORDER BY TOTAL_REGISTRATIONS DESC
LIMIT 25;

-- 10) Data freshness and latest ingestion files
SELECT
  MAX(LOAD_TIMESTAMP) AS LAST_LOAD_TS,
  COUNT(DISTINCT SOURCE_FILE) AS SOURCE_FILES_SEEN,
  COUNT(*) AS TOTAL_ROWS
FROM EV_PROJECT_DB.CONSUMPTION.MV_EV_REGISTRATIONS;
