-- NeonDB/PostgreSQL compatible preamble
CREATE SCHEMA IF NOT EXISTS catalogue;

CREATE TABLE IF NOT EXISTS catalogue.catalog_options_staging (
	manufacturer_name TEXT NOT NULL,
	model_name TEXT NOT NULL,
	ev_type TEXT NOT NULL,
	cafv_type TEXT NOT NULL
);

TRUNCATE TABLE catalogue.catalog_options_staging;

INSERT INTO catalogue.catalog_options_staging (manufacturer_name, model_name, ev_type, cafv_type)
VALUES
('AUDI','A3','Plug-in Hybrid Electric Vehicle (PHEV)','Not eligible due to low battery range'),
('AUDI','A7','Plug-in Hybrid Electric Vehicle (PHEV)','Not eligible due to low battery range'),
('AUDI','A8 E','Plug-in Hybrid Electric Vehicle (PHEV)','Not eligible due to low battery range'),
('AUDI','E-TRON','Battery Electric Vehicle (BEV)','Clean Alternative Fuel Vehicle Eligible'),
('AUDI','E-TRON','Battery Electric Vehicle (BEV)','Eligibility unknown as battery range has not been researched'),
('AUDI','E-TRON GT','Battery Electric Vehicle (BEV)','Eligibility unknown as battery range has not been researched'),
('AUDI','E-TRON SPORTBACK','Battery Electric Vehicle (BEV)','Clean Alternative Fuel Vehicle Eligible'),
('AUDI','E-TRON SPORTBACK','Battery Electric Vehicle (BEV)','Eligibility unknown as battery range has not been researched'),
('AUDI','Q4','Battery Electric Vehicle (BEV)','Eligibility unknown as battery range has not been researched'),
('AUDI','Q5','Plug-in Hybrid Electric Vehicle (PHEV)','Not eligible due to low battery range'),
('AUDI','Q5 E','Plug-in Hybrid Electric Vehicle (PHEV)','Not eligible due to low battery range'),
('AUDI','RS E-TRON GT','Battery Electric Vehicle (BEV)','Eligibility unknown as battery range has not been researched'),
('BENTLEY','FLYING SPUR','Plug-in Hybrid Electric Vehicle (PHEV)','Not eligible due to low battery range'),
('BMW','330E','Plug-in Hybrid Electric Vehicle (PHEV)','Not eligible due to low battery range'),
('BMW','530E','Plug-in Hybrid Electric Vehicle (PHEV)','Not eligible due to low battery range'),
('BMW','740E','Plug-in Hybrid Electric Vehicle (PHEV)','Not eligible due to low battery range'),
('BMW','745LE','Plug-in Hybrid Electric Vehicle (PHEV)','Not eligible due to low battery range'),
('BMW','I3','Battery Electric Vehicle (BEV)','Clean Alternative Fuel Vehicle Eligible'),
('BMW','I3','Battery Electric Vehicle (BEV)','Eligibility unknown as battery range has not been researched'),
('BMW','I3','Plug-in Hybrid Electric Vehicle (PHEV)','Clean Alternative Fuel Vehicle Eligible'),
('BMW','I4','Battery Electric Vehicle (BEV)','Eligibility unknown as battery range has not been researched'),
('BMW','I8','Plug-in Hybrid Electric Vehicle (PHEV)','Not eligible due to low battery range'),
('BMW','IX','Battery Electric Vehicle (BEV)','Eligibility unknown as battery range has not been researched'),
('BMW','X3','Plug-in Hybrid Electric Vehicle (PHEV)','Not eligible due to low battery range'),
('BMW','X5','Plug-in Hybrid Electric Vehicle (PHEV)','Clean Alternative Fuel Vehicle Eligible'),
('BMW','X5','Plug-in Hybrid Electric Vehicle (PHEV)','Not eligible due to low battery range'),
('CADILLAC','CT6','Plug-in Hybrid Electric Vehicle (PHEV)','Clean Alternative Fuel Vehicle Eligible'),
('CADILLAC','ELR','Plug-in Hybrid Electric Vehicle (PHEV)','Clean Alternative Fuel Vehicle Eligible'),
('CHEVROLET','BOLT EUV','Battery Electric Vehicle (BEV)','Eligibility unknown as battery range has not been researched'),
('CHEVROLET','BOLT EV','Battery Electric Vehicle (BEV)','Clean Alternative Fuel Vehicle Eligible'),
('CHEVROLET','BOLT EV','Battery Electric Vehicle (BEV)','Eligibility unknown as battery range has not been researched'),
('CHEVROLET','SPARK','Battery Electric Vehicle (BEV)','Clean Alternative Fuel Vehicle Eligible'),
('CHEVROLET','VOLT','Plug-in Hybrid Electric Vehicle (PHEV)','Clean Alternative Fuel Vehicle Eligible'),
('CHRYSLER','PACIFICA','Plug-in Hybrid Electric Vehicle (PHEV)','Clean Alternative Fuel Vehicle Eligible'),
('FIAT','500','Battery Electric Vehicle (BEV)','Clean Alternative Fuel Vehicle Eligible'),
('FISKER','KARMA','Plug-in Hybrid Electric Vehicle (PHEV)','Clean Alternative Fuel Vehicle Eligible'),
('FORD','C-MAX','Plug-in Hybrid Electric Vehicle (PHEV)','Not eligible due to low battery range'),
('FORD','ESCAPE','Plug-in Hybrid Electric Vehicle (PHEV)','Clean Alternative Fuel Vehicle Eligible'),
('FORD','F-150','Battery Electric Vehicle (BEV)','Eligibility unknown as battery range has not been researched'),
('FORD','FOCUS','Battery Electric Vehicle (BEV)','Clean Alternative Fuel Vehicle Eligible'),
('FORD','FUSION','Plug-in Hybrid Electric Vehicle (PHEV)','Not eligible due to low battery range'),
('FORD','MUSTANG MACH-E','Battery Electric Vehicle (BEV)','Eligibility unknown as battery range has not been researched'),
('FORD','RANGER','Battery Electric Vehicle (BEV)','Clean Alternative Fuel Vehicle Eligible'),
('FORD','TRANSIT','Battery Electric Vehicle (BEV)','Eligibility unknown as battery range has not been researched'),
('GENESIS','G80','Battery Electric Vehicle (BEV)','Eligibility unknown as battery range has not been researched'),
('GENESIS','GV60','Battery Electric Vehicle (BEV)','Eligibility unknown as battery range has not been researched'),
('HONDA','ACCORD','Plug-in Hybrid Electric Vehicle (PHEV)','Not eligible due to low battery range'),
('HONDA','CLARITY','Plug-in Hybrid Electric Vehicle (PHEV)','Clean Alternative Fuel Vehicle Eligible'),
('HYUNDAI','IONIQ','Battery Electric Vehicle (BEV)','Clean Alternative Fuel Vehicle Eligible'),
('HYUNDAI','IONIQ','Battery Electric Vehicle (BEV)','Eligibility unknown as battery range has not been researched'),
('HYUNDAI','IONIQ','Battery Electric Vehicle (BEV)','Not eligible due to low battery range'),
('HYUNDAI','IONIQ','Plug-in Hybrid Electric Vehicle (PHEV)','Not eligible due to low battery range'),
('HYUNDAI','IONIQ 5','Battery Electric Vehicle (BEV)','Eligibility unknown as battery range has not been researched'),
('HYUNDAI','KONA','Battery Electric Vehicle (BEV)','Clean Alternative Fuel Vehicle Eligible'),
('HYUNDAI','KONA ELECTRIC','Battery Electric Vehicle (BEV)','Eligibility unknown as battery range has not been researched'),
('HYUNDAI','SANTA FE','Plug-in Hybrid Electric Vehicle (PHEV)','Clean Alternative Fuel Vehicle Eligible'),
('HYUNDAI','SONATA','Plug-in Hybrid Electric Vehicle (PHEV)','Not eligible due to low battery range'),
('HYUNDAI','TUCSON','Plug-in Hybrid Electric Vehicle (PHEV)','Clean Alternative Fuel Vehicle Eligible'),
('JAGUAR','I-PACE','Battery Electric Vehicle (BEV)','Clean Alternative Fuel Vehicle Eligible'),
('JAGUAR','I-PACE','Battery Electric Vehicle (BEV)','Eligibility unknown as battery range has not been researched'),
('JEEP','GRAND CHEROKEE','Plug-in Hybrid Electric Vehicle (PHEV)','Not eligible due to low battery range'),
('JEEP','WRANGLER','Plug-in Hybrid Electric Vehicle (PHEV)','Not eligible due to low battery range'),
('KIA','EV6','Battery Electric Vehicle (BEV)','Eligibility unknown as battery range has not been researched'),
('KIA','NIRO','Battery Electric Vehicle (BEV)','Clean Alternative Fuel Vehicle Eligible'),
('KIA','NIRO','Battery Electric Vehicle (BEV)','Eligibility unknown as battery range has not been researched'),
('KIA','NIRO','Plug-in Hybrid Electric Vehicle (PHEV)','Not eligible due to low battery range'),
('KIA','OPTIMA','Plug-in Hybrid Electric Vehicle (PHEV)','Not eligible due to low battery range'),
('KIA','SORENTO','Plug-in Hybrid Electric Vehicle (PHEV)','Clean Alternative Fuel Vehicle Eligible'),
('KIA','SOUL','Battery Electric Vehicle (BEV)','Clean Alternative Fuel Vehicle Eligible'),
('KIA','SOUL EV','Battery Electric Vehicle (BEV)','Clean Alternative Fuel Vehicle Eligible'),
('KIA','SOUL EV','Battery Electric Vehicle (BEV)','Eligibility unknown as battery range has not been researched'),
('KIA','SPORTAGE','Plug-in Hybrid Electric Vehicle (PHEV)','Clean Alternative Fuel Vehicle Eligible'),
('LAND ROVER','RANGE ROVER','Plug-in Hybrid Electric Vehicle (PHEV)','Not eligible due to low battery range'),
('LAND ROVER','RANGE ROVER SPORT','Plug-in Hybrid Electric Vehicle (PHEV)','Not eligible due to low battery range'),
('LEXUS','NX','Plug-in Hybrid Electric Vehicle (PHEV)','Clean Alternative Fuel Vehicle Eligible'),
('LINCOLN','AVIATOR','Plug-in Hybrid Electric Vehicle (PHEV)','Not eligible due to low battery range'),
('LINCOLN','CORSAIR','Plug-in Hybrid Electric Vehicle (PHEV)','Not eligible due to low battery range'),
('LUCID MOTORS','LUCID AIR','Battery Electric Vehicle (BEV)','Eligibility unknown as battery range has not been researched'),
('MERCEDES-BENZ','B-CLASS','Battery Electric Vehicle (BEV)','Clean Alternative Fuel Vehicle Eligible'),
('MERCEDES-BENZ','C-CLASS','Plug-in Hybrid Electric Vehicle (PHEV)','Not eligible due to low battery range'),
('MERCEDES-BENZ','EQB-CLASS','Battery Electric Vehicle (BEV)','Eligibility unknown as battery range has not been researched'),
('MERCEDES-BENZ','EQS-CLASS SEDAN','Battery Electric Vehicle (BEV)','Eligibility unknown as battery range has not been researched'),
('MERCEDES-BENZ','EQS-CLASS SUV','Battery Electric Vehicle (BEV)','Eligibility unknown as battery range has not been researched'),
('MERCEDES-BENZ','GLC-CLASS','Plug-in Hybrid Electric Vehicle (PHEV)','Not eligible due to low battery range'),
('MERCEDES-BENZ','GLE-CLASS','Plug-in Hybrid Electric Vehicle (PHEV)','Not eligible due to low battery range'),
('MERCEDES-BENZ','S-CLASS','Plug-in Hybrid Electric Vehicle (PHEV)','Not eligible due to low battery range'),
('MINI','COUNTRYMAN','Plug-in Hybrid Electric Vehicle (PHEV)','Not eligible due to low battery range'),
('MINI','HARDTOP','Battery Electric Vehicle (BEV)','Clean Alternative Fuel Vehicle Eligible'),
('MINI','HARDTOP','Battery Electric Vehicle (BEV)','Eligibility unknown as battery range has not been researched'),
('MITSUBISHI','I-MIEV','Battery Electric Vehicle (BEV)','Clean Alternative Fuel Vehicle Eligible'),
('MITSUBISHI','OUTLANDER','Plug-in Hybrid Electric Vehicle (PHEV)','Not eligible due to low battery range'),
('NISSAN','LEAF','Battery Electric Vehicle (BEV)','Clean Alternative Fuel Vehicle Eligible'),
('NISSAN','LEAF','Battery Electric Vehicle (BEV)','Eligibility unknown as battery range has not been researched'),
('POLESTAR','PS2','Battery Electric Vehicle (BEV)','Clean Alternative Fuel Vehicle Eligible'),
('POLESTAR','PS2','Battery Electric Vehicle (BEV)','Eligibility unknown as battery range has not been researched'),
('PORSCHE','CAYENNE','Plug-in Hybrid Electric Vehicle (PHEV)','Not eligible due to low battery range'),
('PORSCHE','PANAMERA','Plug-in Hybrid Electric Vehicle (PHEV)','Not eligible due to low battery range'),
('PORSCHE','TAYCAN','Battery Electric Vehicle (BEV)','Clean Alternative Fuel Vehicle Eligible'),
('PORSCHE','TAYCAN','Battery Electric Vehicle (BEV)','Eligibility unknown as battery range has not been researched'),
('RIVIAN','EDV','Battery Electric Vehicle (BEV)','Eligibility unknown as battery range has not been researched'),
('RIVIAN','R1S','Battery Electric Vehicle (BEV)','Eligibility unknown as battery range has not been researched'),
('RIVIAN','R1T','Battery Electric Vehicle (BEV)','Eligibility unknown as battery range has not been researched'),
('SMART','EQ FORTWO','Battery Electric Vehicle (BEV)','Clean Alternative Fuel Vehicle Eligible'),
('SMART','FORTWO','Battery Electric Vehicle (BEV)','Clean Alternative Fuel Vehicle Eligible'),
('SMART','FORTWO ELECTRIC DRIVE','Battery Electric Vehicle (BEV)','Clean Alternative Fuel Vehicle Eligible'),
('SUBARU','CROSSTREK','Plug-in Hybrid Electric Vehicle (PHEV)','Not eligible due to low battery range'),
('SUBARU','SOLTERRA','Battery Electric Vehicle (BEV)','Eligibility unknown as battery range has not been researched'),
('TESLA','MODEL 3','Battery Electric Vehicle (BEV)','Clean Alternative Fuel Vehicle Eligible'),
('TESLA','MODEL 3','Battery Electric Vehicle (BEV)','Eligibility unknown as battery range has not been researched'),
('TESLA','MODEL S','Battery Electric Vehicle (BEV)','Clean Alternative Fuel Vehicle Eligible'),
('TESLA','MODEL S','Battery Electric Vehicle (BEV)','Eligibility unknown as battery range has not been researched'),
('TESLA','MODEL X','Battery Electric Vehicle (BEV)','Clean Alternative Fuel Vehicle Eligible'),
('TESLA','MODEL X','Battery Electric Vehicle (BEV)','Eligibility unknown as battery range has not been researched'),
('TESLA','MODEL Y','Battery Electric Vehicle (BEV)','Clean Alternative Fuel Vehicle Eligible'),
('TESLA','MODEL Y','Battery Electric Vehicle (BEV)','Eligibility unknown as battery range has not been researched'),
('TESLA','ROADSTER','Battery Electric Vehicle (BEV)','Clean Alternative Fuel Vehicle Eligible'),
('TH!NK','CITY','Battery Electric Vehicle (BEV)','Clean Alternative Fuel Vehicle Eligible'),
('TOYOTA','BZ4X','Battery Electric Vehicle (BEV)','Eligibility unknown as battery range has not been researched'),
('TOYOTA','PRIUS PLUG-IN','Plug-in Hybrid Electric Vehicle (PHEV)','Not eligible due to low battery range'),
('TOYOTA','PRIUS PRIME','Plug-in Hybrid Electric Vehicle (PHEV)','Not eligible due to low battery range'),
('TOYOTA','RAV4','Battery Electric Vehicle (BEV)','Clean Alternative Fuel Vehicle Eligible'),
('TOYOTA','RAV4 PRIME','Plug-in Hybrid Electric Vehicle (PHEV)','Clean Alternative Fuel Vehicle Eligible'),
('VOLKSWAGEN','E-GOLF','Battery Electric Vehicle (BEV)','Clean Alternative Fuel Vehicle Eligible'),
('VOLKSWAGEN','ID.4','Battery Electric Vehicle (BEV)','Eligibility unknown as battery range has not been researched'),
('VOLVO','C40','Battery Electric Vehicle (BEV)','Eligibility unknown as battery range has not been researched'),
('VOLVO','S60','Plug-in Hybrid Electric Vehicle (PHEV)','Clean Alternative Fuel Vehicle Eligible'),
('VOLVO','S60','Plug-in Hybrid Electric Vehicle (PHEV)','Not eligible due to low battery range'),
('VOLVO','S90','Plug-in Hybrid Electric Vehicle (PHEV)','Not eligible due to low battery range'),
('VOLVO','V60','Plug-in Hybrid Electric Vehicle (PHEV)','Clean Alternative Fuel Vehicle Eligible'),
('VOLVO','V60','Plug-in Hybrid Electric Vehicle (PHEV)','Not eligible due to low battery range'),
('VOLVO','XC40','Battery Electric Vehicle (BEV)','Eligibility unknown as battery range has not been researched'),
('VOLVO','XC60','Plug-in Hybrid Electric Vehicle (PHEV)','Clean Alternative Fuel Vehicle Eligible'),
('VOLVO','XC60','Plug-in Hybrid Electric Vehicle (PHEV)','Not eligible due to low battery range'),
('VOLVO','XC90','Plug-in Hybrid Electric Vehicle (PHEV)','Clean Alternative Fuel Vehicle Eligible'),
('VOLVO','XC90','Plug-in Hybrid Electric Vehicle (PHEV)','Not eligible due to low battery range');
